# Generated by Django 6.1 on 2026-08-28 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('technologies', models.CharField()),
                ('url', models.CharField()),
                ('githubrepo', models.CharField(blank=True, db_column='githubRepo', default='')),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
    ]
