# Generated by Django 6.1 on 2026-08-28 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jobname', models.CharField(db_column='jobName')),
                ('date', models.CharField()),
                ('jobposition', models.TextField(db_column='jobPosition')),
            ],
            options={
                'db_table': 'experience',
                'managed': False,
            },
        ),
    ]
